#!/bin/bash
#SBATCH --job-name=sa
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=48:00:00
#SBATCH --mem-per-cpu=4000
#SBATCH --partition=skylake
#SBATCH --gres=gpu:1

module load python/3.8.5
module load pytorch/1.7.1-python-3.8.5
module load scipy/1.6.0-python-3.8.5
module load scikit-learn/0.24.2-python-3.8.5

python3 ./ozstar_train.py --res 219 --subj 0 --epoch 10 --batch 1 --sample 1 --hu 100 --lr 0.005 --save results/train/train_1/train_sa_r219_su0_b1_sa1_hu100_lr005.pt --nolog
python3 ./ozstar_train.py --res 219 --subj 0 --epoch 10 --batch 1 --sample 10 --hu 100 --lr 0.005 --save results/train/train_10/train_sa_r219_su0_b1_sa10_hu100_lr005.pt --nolog
python3 ./ozstar_train.py --res 219 --subj 0 --epoch 10 --batch 1 --sample 100 --hu 100 --lr 0.005 --save results/train/train_100/train_sa_r219_su0_b1_sa100_hu100_lr005.pt --nolog
python3 ./ozstar_train.py --res 219 --subj 0 --epoch 10 --batch 1 --sample 1000 --hu 100 --lr 0.005 --save results/train/train_1000/train_sa_r219_su0_b1_sa1000_hu100_lr005.pt --nolog
python3 ./ozstar_train.py --res 219 --subj 0 --epoch 10 --batch 1 --sample 10000 --hu 100 --lr 0.005 --save results/train/train_10000/train_sa_r219_su0_b1_sa10000_hu100_lr005.pt --nolog

python3 ./ozstar_cv.py --res 219 --batch 1 --sample 1 --load results/train/train_1/train_sa_r219_su0_b1_sa1_hu100_lr005.pt --save results/cv/cv_1/cv_sa_r219_su0_b1_sa1_hu100_lr005.pt --nolog
python3 ./ozstar_cv.py --res 219 --batch 1 --sample 10 --load results/train/train_10/train_sa_r219_su0_b1_sa10_hu100_lr005.pt --save results/cv/cv_10/cv_sa_r219_su0_b1_sa10_hu100_lr005.pt --nolog
python3 ./ozstar_cv.py --res 219 --batch 1 --sample 100 --load results/train/train_100/train_sa_r219_su0_b1_sa100_hu100_lr005.pt --save results/cv/cv_100/cv_sa_r219_su0_b1_sa100_hu100_lr005.pt --nolog
python3 ./ozstar_cv.py --res 219 --batch 1 --sample 1000 --load results/train/train_1000/train_sa_r219_su0_b1_sa1000_hu100_lr005.pt --save results/cv/cv_1000/cv_sa_r219_su0_b1_sa1000_hu100_lr005.pt --nolog
python3 ./ozstar_cv.py --res 219 --batch 1 --sample 10000 --load results/train/train_10000/train_sa_r219_su0_b1_sa10000_hu100_lr005.pt --save results/cv/cv_10000/cv_sa_r219_su0_b1_sa10000_hu100_lr005.pt --nolog