#!/bin/bash
#SBATCH --job-name=b
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=48:00:00
#SBATCH --mem-per-cpu=4000
#SBATCH --partition=skylake
#SBATCH --gres=gpu:1

module load python/3.8.5
module load pytorch/1.7.1-python-3.8.5
module load scipy/1.6.0-python-3.8.5
module load scikit-learn/0.24.2-python-3.8.5

python3 ./ozstar_train.py --res 219 --subj 0 --epoch 10 --batch 1 --sample 100 --hu 100 --lr 0.005 --save results/train/train_1/train_b_r219_su0_b1_sa100_hu100_lr005.pt --nolog
python3 ./ozstar_train.py --res 219 --subj 0 --epoch 10 --batch 2 --sample 100 --hu 100 --lr 0.005 --save results/train/train_2/train_b_r219_su0_b2_sa100_hu100_lr005.pt --nolog
python3 ./ozstar_train.py --res 219 --subj 0 --epoch 10 --batch 4 --sample 100 --hu 100 --lr 0.005 --save results/train/train_4/train_b_r219_su0_b4_sa100_hu100_lr005.pt --nolog
python3 ./ozstar_train.py --res 219 --subj 0 --epoch 10 --batch 73 --sample 100 --hu 100 --lr 0.005 --save results/train/train_73/train_b_r219_su0_b73_sa100_hu100_lr005.pt --nolog
python3 ./ozstar_train.py --res 219 --subj 0 --epoch 10 --batch 146 --sample 100 --hu 100 --lr 0.005 --save results/train/train_146/train_b_r219_su0_b146_sa100_hu100_lr005.pt --nolog
python3 ./ozstar_train.py --res 219 --subj 0 --epoch 10 --batch 292 --sample 100 --hu 100 --lr 0.005 --save results/train/train_292/train_b_r219_su0_b292_sa100_hu100_lr005.pt --nolog

python3 ./ozstar_cv.py --res 219 --batch 1 --sample 100 --load results/train/train_1/train_b_r219_su0_b1_sa100_hu100_lr005.pt --save results/cv/cv_1/cv_b_r219_su0_b1_sa100_hu100_lr005.pt --nolog
python3 ./ozstar_cv.py --res 219 --batch 2 --sample 100 --load results/train/train_2/train_b_r219_su0_b2_sa100_hu100_lr005.pt --save results/cv/cv_2/cv_b_r219_su0_b2_sa100_hu100_lr005.pt --nolog
python3 ./ozstar_cv.py --res 219 --batch 4 --sample 100 --load results/train/train_4/train_b_r219_su0_b4_sa100_hu100_lr005.pt --save results/cv/cv_4/cv_b_r219_su0_b4_sa100_hu100_lr005.pt --nolog
python3 ./ozstar_cv.py --res 219 --batch 73 --sample 100 --load results/train/train_73/train_b_r219_su0_b73_sa100_hu100_lr005.pt --save results/cv/cv_73/cv_b_r219_su0_b73_sa100_hu100_lr005.pt --nolog
python3 ./ozstar_cv.py --res 219 --batch 146 --sample 100 --load results/train/train_146/train_b_r219_su0_b146_sa100_hu100_lr005.pt --save results/cv/cv_146/cv_b_r219_su0_b146_sa100_hu100_lr005.pt --nolog
python3 ./ozstar_cv.py --res 219 --batch 292 --sample 100 --load results/train/train_292/train_b_r219_su0_b292_sa100_hu100_lr005.pt --save results/cv/cv_292/cv_b_r219_su0_b292_sa100_hu100_lr005.pt --nolog