#!/bin/bash
#SBATCH --job-name=hu_cv
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=48:00:00
#SBATCH --mem-per-cpu=4000
#SBATCH --partition=skylake
#SBATCH --gres=gpu:1

module load python/3.8.5
module load pytorch/1.7.1-python-3.8.5
module load scipy/1.6.0-python-3.8.5
module load scikit-learn/0.24.2-python-3.8.5

python3 ./ozstar_ml.py --res 219 --batch 1 --sample 100 --load results/r219_su0_e10_b1_sa100_hu1_lr005.pt --save results/cv_r219_su0_e10_b1_sa100_hu1_lr005.pt --nolog
python3 ./ozstar_ml.py --res 219 --batch 1 --sample 100 --load results/r219_su0_e10_b1_sa100_hu10_lr005.pt --save results/cv_r219_su0_e10_b1_sa100_hu10_lr005.pt --nolog
python3 ./ozstar_ml.py --res 219 --batch 1 --sample 100 --load results/r219_su0_e10_b1_sa100_hu100_lr005.pt --save results/cv_r219_su0_e10_b1_sa100_hu100_lr005.pt --nolog
python3 ./ozstar_ml.py --res 219 --batch 1 --sample 100 --load results/r219_su0_e10_b1_sa100_hu1000_lr005.pt --save results/cv_r219_su0_e10_b1_sa100_hu1000_lr005.pt --nolog
