#!/bin/bash
#SBATCH --job-name=demo_ml
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=01:00:00
#SBATCH --mem-per-cpu=4000
#SBATCH --partition=skylake
#SBATCH --gres=gpu:1

module load python/3.8.5
module load pytorch/1.7.1-python-3.8.5
module load scipy/1.6.0-python-3.8.5
module load scikit-learn/0.24.2-python-3.8.5

python3 ./ozstar_ml.py --res 219 --subj 0 --epoch 1 --batch 1 --sample 64 --hu 2000 --lr 0.005 --save results/demo.pt > log.txt
